FROM registry.access.redhat.com/ubi8/ubi:latest AS builder
ADD --chown=107:107 https://download.cirros-cloud.net/0.6.3/cirros-0.6.3-x86_64-disk.img /disk/ 
RUN chmod 0440 /disk/*

FROM scratch
COPY --from=builder /disk/* /disk/
