---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  measurements:
    - name: jobLatency
metricsEndpoints:

{{ if .ES_SERVER }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      insecureSkipVerify: true
      esServers: [{{.ES_SERVER}}]
      defaultIndex: {{.ES_INDEX}}
      type: opensearch      
{{ end }}
{{ if .LOCAL_INDEXING }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      type: local
      metricsDirectory: collected-metrics-{{.UUID}}
{{ end }}
  
jobs:

  - name: prereqs
    jobIterations: 1
    skipIndexing: true
    qps: 10
    burst: 10
    objects:
      - objectTemplate: cluster-queue.yml
        replicas: {{.ITERATIONS}}
        inputVars:
          PODS_QUOTA: {{.PODS_QUOTA}}
      - objectTemplate: resource-flavor.yml
        replicas: 1

  - name: kueue-scale-jobs-shared
    namespace: kueue-scale
    jobIterations: {{.ITERATIONS}}
    preLoadImages: true
    preLoadPeriod: 10s
    namespacedIterations: true
    cleanup: true
    namespaceLabels:
      kueue.openshift.io/managed: "true"
    qps: {{.QPS}}
    burst: {{.BURST}}
    objects:
      - objectTemplate: local-queue.yml
        replicas: 1
      - objectTemplate: job.yml
        replicas: {{.JOB_REPLICAS}}
        inputVars:
          parallelism: {{.PARALLELISM}}
          runtime: {{.WORKLOAD_RUNTIME}}
