apiVersion: v1
kind: ConfigMap
metadata:
  name: spiffe-helper-config
  namespace: ztwim-perf
data:
  helper.conf: |
    agent_address = "/spiffe-workload-api/spire-agent.sock"
    cert_dir = "/certs"
    svid_file_name = "svid.pem"
    svid_key_file_name = "svid_key.pem"
    svid_bundle_file_name = "bundle.pem"
