---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: server-{{.Replica}}
spec:
  replicas: {{.podReplicas}}
  selector:
    matchLabels:
      name: cluster-density-{{.Replica}}
  template:
    metadata:
      labels:
        name: cluster-density-{{.Replica}}
        app: nginx
    spec:
      topologySpreadConstraints:
      - maxSkew: 1 
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway 
        labelSelector: 
          matchLabels:
            app: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
              - key: node-role.kubernetes.io/workload
                operator: DoesNotExist
      containers:
      - image: quay.io/cloud-bulldozer/nginx:latest
        resources:
          requests:
            memory: "25Mi"
            cpu: "25m"
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podlabels
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        name: cluster-density
      volumes:
      - name: podinfo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
