apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: virt-server-{{.Iteration}}
  labels:
    kubevirt.io/os: fedora
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/os: fedora
        app: nginx
    spec:
      terminationGracePeriodSeconds: 0
      domain:
        resources:
          requests:
            memory: 256Mi
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - disk:
              bus: virtio
            name: cloudinitdisk
          - name: emptydisk
            disk:
              bus: virtio
          interfaces:
          - name: primary-udn-net
            binding:
              name: {{.bindingMethod}}
            ports:
            - port: 80
      networks:
      - name: primary-udn-net
        pod: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: {{.vmImage}}
          imagePullPolicy: IfNotPresent
      - name: cloudinitdisk
        cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              eth0:
                dhcp4: true
                addresses: [10.132.0.5/24]
          userData: |-
            #cloud-config
            password: perfscale
            chpasswd: { expire: False }
            packages:
              - nginx
            runcmd:
              - systemctl start nginx
              - systemctl enable nginx
      - name: emptydisk
        emptyDisk:
          capacity: "50Mi"
