apiVersion: v1
kind: Secret
metadata:
  name: {{.providerName}}-creds
  namespace: {{.Namespace}}
  labels:
    inference.networking.k8s.io/bbr-managed: "true"
type: Opaque
stringData:
  api-key: "maas-perf-test-dummy-key"
