apiVersion: v1
kind: Service
metadata:
  name: llm-d-inference-sim
  namespace: {{.Namespace}}
spec:
  type: ClusterIP
  selector:
    app: llm-d-inference-sim
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
