---
global:
  gc: false
  gcMetrics: false
  deletionStrategy: default


metricsEndpoints:
  - indexer:
      type: local
      metricsDirectory: collected-metrics-build-farm

jobs:
  - name: build-farm-create
    namespace: build-farm-tenant
    jobIterations: {{ .JOB_ITERATIONS }}
    namespacedIterations: {{ .NAMESPACED_ITERATIONS }}
    iterationsPerNamespace: {{ .ITERATIONS_PER_NAMESPACE }}
    preLoadImages: false
    qps: {{.QPS}}
    burst: {{.BURST}}
    watchers:
      - kind: Pod
        replicas: 1
        apiVersion: v1
      - kind: Job
        replicas: 1
        apiVersion: batch/v1
    objects:
      - objectTemplate: cmd/config/build-farm/build-job-large.yml
        replicas: 1
        wait: false
        inputVars:
          buildImage: "quay.io/konflux-ci/buildah-task:latest"
          buildPlatform: "linux/x86_64"
          targetImage: "registry.local/build-farm/test-image"
          enableCustomAnnotation: "false"
          deletionPercentage: "30"
          jobIterations: {{ .JOB_ITERATIONS }}

  - name: build-farm-update-metadata
    namespace: build-farm-tenant
    jobIterations: 1
    namespacedIterations: {{ .NAMESPACED_ITERATIONS }}
    iterationsPerNamespace: {{ .ITERATIONS_PER_NAMESPACE }}
    preLoadImages: false
    jobType: patch
    qps: {{.QPS}}
    burst: {{.BURST}}
    objects:
      - kind: Pod
        labelSelector: {build.farm.redhat.com/patch: true}
        objectTemplate: cmd/config/build-farm/patch_update_metadata_pod.yml
        replicas: 1
        patchType: "application/apply-patch+yaml"
        apiVersion: v1
      - kind: Job
        labelSelector: {build.farm.redhat.com/patch: true}
        objectTemplate: cmd/config/build-farm/patch_update_metadata_job.yml
        replicas: 1
        patchType: "application/apply-patch+yaml"
        apiVersion: batch/v1

  - name: build-farm-delete
    namespace: build-farm-tenant
    jobIterations: 1
    namespacedIterations: {{ .NAMESPACED_ITERATIONS }}
    iterationsPerNamespace: {{ .ITERATIONS_PER_NAMESPACE }}
    preLoadImages: false
    jobType: delete
    qps: {{.QPS}}
    burst: {{.BURST}}
    objects:
      - kind: Pod
        labelSelector: {build.farm.redhat.com/delete: true}
        replicas: 1
        apiVersion: v1
      - kind: Job
        labelSelector: {build.farm.redhat.com/delete: true}
        replicas: 1
        apiVersion: batch/v1

  - name: build-farm-wait-create
    namespace: build-farm-tenant
    jobIterations: {{ .JOB_ITERATIONS }}
    namespacedIterations: {{ .NAMESPACED_ITERATIONS }}
    iterationsPerNamespace: {{ .ITERATIONS_PER_NAMESPACE }}
    preLoadImages: false
    errorOnVerify: false
    qps: {{.QPS}}
    burst: {{.BURST}}
    watchers:
      - kind: Pod
        labelSelector: {app.kubernetes.io/managed-by: kube-burner}
        replicas: 1
        apiVersion: v1
      - kind: Job
        labelSelector: {app.kubernetes.io/managed-by: kube-burner}
        replicas: 1
        apiVersion: batch/v1
    objects:
      - objectTemplate: cmd/config/build-farm/build-job-large.yml
        replicas: 1
        inputVars:
          buildImage: "quay.io/konflux-ci/buildah-task:latest"
          buildPlatform: "linux/x86_64"
          targetImage: "registry.local/build-farm/test-image"
          deletionPercentage: "30"
          jobIterations: {{ .JOB_ITERATIONS }}
