---
apiVersion: v1
kind: Secret
metadata:
  name: {{.JobName}}-common-secret-{{.Replica}}
stringData:
{{- range $i := untilStep 0 (.commonSecretFiles | int) 1 }}
  file-{{ $i }}: "{{ randAlphaNum ($.commonSecretFileSize | int) }}"
{{- end }}
