---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.JobName}}-unique-cm-{{.Replica}}
data:
{{- range $i := untilStep 0 (.uniqueKV | int) 1 }}
  key-{{ $i }}: "{{ randAlphaNum ($.uniqueKVLen | int) }}"
{{- end }}
