---
apiVersion: v1
kind: Secret
metadata:
  name: {{.JobName}}-unique-secret-{{.Replica}}
stringData:
{{- range $i := untilStep 0 (.uniqueKV | int) 1 }}
  key-{{ $i }}: "{{ randAlphaNum ($.uniqueKVLen | int) }}"
{{- end }}
