apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue"
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: [pods]
    flavors:
    - name: "default"
      resources:
      - name: "pods"
        nominalQuota: {{.PODS_QUOTA}}
