---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  measurements:
    - name: podLatency
metricsEndpoints:
{{ if .ES_SERVER }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      insecureSkipVerify: true
      esServers: [{{.ES_SERVER}}]
      defaultIndex: {{.ES_INDEX}}
      type: opensearch      
{{ end }}
{{ if .LOCAL_INDEXING }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      type: local
      metricsDirectory: collected-metrics-{{.UUID}}
{{ end }}
  
jobs:

  - name: prereqs
    jobIterations: 1
    namespace: kueue-scale
    preLoadImages: false
    namespacedIterations: false
    cleanup: true
    skipIndexing: true
    qps: 5
    burst: 5
    objects:
      - objectTemplate: cluster-queue.yml
        replicas: 1
        inputVars:
          PODS_QUOTA: {{.POD_REPLICAS}}
      - objectTemplate: resource-flavor.yml
        replicas: 1

  - name: kueue-scale-pods
    namespace: kueue-scale
    jobIterations: {{.ITERATIONS}}
    preLoadImages: true
    preLoadPeriod: 10s
    namespacedIterations: false
    cleanup: true
    namespaceLabels:
      kueue.openshift.io/managed: "true"
    qps: {{.QPS}}
    burst: {{.BURST}}
    objects:
      - objectTemplate: local-queue.yml
        replicas: 1
      - objectTemplate: pod.yml
        replicas: {{.POD_REPLICAS}}
