apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: webserver-{{.Replica}}-{{.Iteration}}
  labels:
    app: webserver
    kubevirt.io/os: fedora
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        name: webserver-{{.Replica}}-{{.Iteration}}
        app: webserver
        kubevirt.io/os: fedora
    spec:
      terminationGracePeriodSeconds: 0
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: webserver
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
              - key: node-role.kubernetes.io/workload
                operator: DoesNotExist
      domain:
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - name: default
            binding:
              name: l2bridge
      networks:
      - name: default
        pod: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: {{.vmImage}}
          imagePullPolicy: IfNotPresent
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: perfscale
            chpasswd: { expire: False }
            runcmd:
              - dnf install -y --nodocs httpd
              - httpd -p 8080 -h /var/www/html
