---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
metricsEndpoints:
{{ if .ES_SERVER }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      esServers: ["{{.ES_SERVER}}"]
      insecureSkipVerify: true
      defaultIndex: {{.ES_INDEX}}
      type: opensearch
{{ end }}
{{ if .LOCAL_INDEXING }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      type: local
      metricsDirectory: collected-metrics-{{.UUID}}
{{ end }}
jobs:
  - name: crd-scale
    jobIterations: {{.KB_CHUNKS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: false
    waitWhenFinished: true
    objects:
      - objectTemplate: example-crd.yml
        replicas: 1
        waitOptions:
          customStatusPaths:
          - key: '(.conditions.[] | select(.type == "Established")).status'
            value: "True"

  - name: db-quota-pressure
    namespace: db-quota-pressure
    cleanup: false
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    iterationsPerNamespace: {{.ITERATIONS_PER_NAMESPACE}}
    podWait: false
    waitWhenFinished: true
    verifyObjects: false
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:
      - objectTemplate: kubeburner-{{.KB_SIZE}}kb.yml
        replicas: {{.KB_CHUNKS}}
