---
kind: Service
apiVersion: v1
metadata:
  name: rds-{{add .Replica 1}}
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: http1
      protocol: TCP
      port: 81
      targetPort: 8080
    - name: http2
      protocol: TCP
      port: 82
      targetPort: 8080
    - name: http3
      protocol: TCP
      port: 83
      targetPort: 8080
    - name: http4
      protocol: TCP
      port: 84
      targetPort: 8080
    - name: http5
      protocol: TCP
      port: 85
      targetPort: 8080
    - name: http6
      protocol: TCP
      port: 86
      targetPort: 8080
