kind: Deployment
apiVersion: apps/v1
metadata:
  name: curl-{{.Replica}}-{{.Iteration}}
spec:
  template:
    metadata:
      labels:
        name: curl-{{.Replica}}-{{.Iteration}}
        app: curl
      annotations:
        test: ovsperf
{{if gt .numSriovs 0}}
        k8s.v1.cni.cncf.io/networks: '[{{range $i := untilStep 1 (int (add .numSriovs 1)) 1}}{{if ne $i 1}},{{end}}{"name":"{{$.sriovNetworkName}}","interface":"sriov{{$i}}"}{{end}}]'
{{end}}
{{if .perfProfile}}
        irq-load-balancing.crio.io: "disable"
        cpu-quota.crio.io: "disable"
{{end}}
    spec:
{{if .perfProfile}}
      runtimeClassName: performance-{{.perfProfile}}
{{end}}
      topologySpreadConstraints:
      - maxSkew: 1 
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway 
        labelSelector: 
          matchLabels:
            app: curl
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: {{.nodeSelector|toJson}}
      containers:
      - name: curlapp
        image: quay.io/cloud-bulldozer/curl:latest
        command: ["sleep", "inf"]
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
        env:
        - name: WEBSERVER_HOSTNAME
          value: webserver-{{.Replica}}-{{.Iteration}}
        - name: WEBSERVER_PORT
          value: "8080"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        startupProbe:
          exec:
            command: 
              - "/bin/sh"
              - "-c"
              - "curl --fail -sS ${WEBSERVER_HOSTNAME}:${WEBSERVER_PORT} -o /dev/null"
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold: 600
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      name: curl-{{.Replica}}-{{.Iteration}}
  strategy:
    type: RollingUpdate
