---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: {{ .sriovNetworkName }}
  namespace: openshift-sriov-network-operator
spec:
  ipam: |
    {
      "type": "whereabouts",
      "range": "172.20.0.0/16"
    }
  logLevel: info
  networkNamespace: node-density-cni-0
  resourceName: {{ .sriovNetDevicepool }}
  spoofChk: "off"
  trust: "on"

