---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ .cloneDataVolumeName }}
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  source:
    pvc:
      namespace: {{ .baseVMNamespace }}
      name: {{ .baseVMRootDiskPVCName }}
  storage:
    accessModes:
    - {{ .accessMode }}
    resources:
      requests:
        storage: {{ default "5Gi" .rootVolumeSize }}
    storageClassName: {{ .storageClassName }}
...