
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: cudn-l3-{{.Iteration}}
spec:
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values: ["cudn-density-pods-{{.Iteration}}"]
  network:
    topology: Layer3
    layer3:
        role: Primary
        subnets:
          - cidr: 10.132.0.0/16
            hostSubnet: 24
        mtu: 1300
