apiVersion: cdi.kubevirt.io/v1beta1
kind: DataSource
metadata:
  name: {{ .baseDataSourceName }}
spec:
  source:
    {{ if .useSnapshot }}
    snapshot:
      name: {{ .baseDataSourceSnapshotName }}
      namespace: {{ .namespace }}
    {{ else }}
    pvc:
      name: {{ .baseDataSourcePVCName }}
      namespace: {{ .namespace }}
    {{ end }}
