---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "{{ .dataVolumeName }}-{{ .Iteration }}-{{ .Replica }}"
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  sourceRef:
    kind: DataSource
    name: {{ .dataSourceName }}
    namespace: {{ .dataSourceNamespace }}
  storage:
    accessModes:
    - {{ .accessMode }}
    resources:
      requests:
        storage: {{ .dataVolumeSize }}
    storageClassName: {{ .storageClassName }}
...