---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ .baseDataVolumeName }}
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  source:
    registry:
      url: {{ .baseDataVolumeUrl }}
  storage:
    accessModes:
    - {{ .accessMode }}
    resources:
      requests:
        storage: {{ .baseDataVolumeSize }}
    storageClassName: {{ .storageClassName }}
...