{
 "title": "kube-burner-virt-density-benchmark",
 "time": { "from": "2017-07-23T03:05:06.532Z", "to": "2033-07-19T03:05:06.532Z" },
 "templating": {
  "list": [
   { "name": "DS_ELASTICSEARCH", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "uuid",
    "label": "Run UUID",
    "query": "{\"find\": \"terms\",\"field\": \"uuid.keyword\",\"query\": \"jobName.keyword:\\\"virt-density\\\"\"}"
   },
   { "name": "percentile", "label": "Latency Percentile", "query": "50, 90, 95, 99" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# **🚀 kube-burner-ocp virt density benchmark dashboard**\n\nThis dashboard provides deep insights into the results of the virt-density benchmark execution using kube-burner-ocp. For a deep dive into workload parameters and metric definitions, refer to the [official kube-burner-ocp documentation](https://kube-burner.github.io/kube-burner-ocp/latest/#virt-density).\n\n### ⚙️ How to configure your view\n\nUse the dropdown selectors at the top of the dashboard to filter the results:\n\n- **Run UUID 🔽:** Select the unique identifier for your benchmark execution to filter all visualizations for that specific test run.\n- **Latency Percentile 📊:** Toggle between median (50th) for typical performance or tail latencies (90th/95th/99th) to identify worst-case bottlenecks in your infrastructure.\n\n📌 **NOTE:**\n- All latency metrics in this dashboard are reported in seconds.\n- Since the OS image is pulled directly into the `virt-launcher` pod’s local directory (typically on the node’s root disk), no DataVolumes or PVCs are created or bound for this scenario."
   }
  },
  { "title": "Environment details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "OpenShift version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ocpVersion.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "metricName.keyword: \"jobSummary\" AND jobConfig.name.keyword: \"virt-density\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Control plane node count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "masterNodesCount", "id": "1", "type": "avg" }
     ],
     "query": "metricName.keyword: \"jobSummary\" AND jobConfig.name.keyword: \"virt-density\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Worker node count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "workerNodesCount", "id": "1", "type": "avg" }
     ],
     "query": "metricName.keyword: \"jobSummary\" AND jobConfig.name.keyword: \"virt-density\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Global performance overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Run details",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "jobConfig.name.keyword:\"virt-density\" AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total benchmark duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total execution duration",
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "sum" }
     ],
     "query": "metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Worker nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "nodeName.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "jobName.keyword:\"virt-density\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VMs created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmName.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "jobName.keyword:\"virt-density\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "VM ready latency analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Avg VM ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Avg VM Ready Latency",
     "bucketAggs": [
      {
       "field": "vmiName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"virt-density\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "P$percentile VM ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "P$percentile VM Ready Latency",
     "bucketAggs": [
      {
       "field": "vmiName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"virt-density\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 10 slowest VMs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "vmiName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"virt-density\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Infrastructure & Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Distribution of VMs per host",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "nodeName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "jobName.keyword:\"virt-density\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM ready latency per host (Average)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "nodeName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"virt-density\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM ready latency per host  (Percentile $percentile)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "nodeName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "vmiName.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"virt-density\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}