{
 "title": "kube-burner-virt-capacity-benchmark",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_ELASTICSEARCH", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "uuid",
    "label": "Run UUID",
    "query": "{\"find\": \"terms\",\"field\": \"uuid.keyword\",\"query\": \"jobName.keyword:\\\"create-vms-0\\\"\"}"
   },
   { "name": "percentile", "label": "Latency Percentile", "query": "50, 90, 95, 99" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# **🚀 kube-burner-ocp virt capacity benchmark dashboard**\n\nThis dashboard provides deep insights into the results of the virt-capacity-benchmark execution using kube-burner-ocp. For a deep dive into workload parameters and metric definitions, refer to the [official kube-burner-ocp documentation](https://kube-burner.github.io/kube-burner-ocp/latest/#virt-capacity-benchmark).\n\n### ⚙️ How to configure your view\n\nUse the dropdown selectors at the top of the dashboard to filter the results:\n\n- **Run UUID 🔽:** Select the unique identifier for your benchmark execution to filter all visualizations for that specific test run.\n- **Latency Percentile 📊:** Toggle between median (50th) for typical performance or tail latencies (90th/95th/99th) to identify worst-case bottlenecks in your infrastructure.\n\n📌 **NOTE:**\n- All latency metrics in this dashboard are reported in seconds.\n- Since the OS image is provisioned through persistent storage instead of being pulled directly into the `virt-launcher` pod’s local directory, this scenario results in the creation and binding of DataVolumes and PVCs."
   }
  },
  { "title": "Environment details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "OpenShift version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ocpVersion.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "metricName.keyword: \"jobSummary\" AND jobConfig.name.keyword: \"create-vms-0\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Control plane node count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "masterNodesCount", "id": "1", "type": "avg" }
     ],
     "query": "metricName.keyword: \"jobSummary\" AND jobConfig.name.keyword: \"create-vms-0\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Worker node count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "workerNodesCount", "id": "1", "type": "avg" }
     ],
     "query": "metricName.keyword: \"jobSummary\" AND jobConfig.name.keyword: \"create-vms-0\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Global performance overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Run details",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "1" }, "type": "logs" }
     ],
     "query": "jobConfig.name.keyword:\"create-vms-0\" AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total benchmark duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total execution duration",
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "sum" }
     ],
     "query": "metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Iterations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "jobName.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VMs created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "VMs created",
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Data Volumes created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Data Volumes created",
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Average phase duration comparison",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "alias": "1. Create VMs",
     "bucketAggs": [
      {
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword:create-vms-* AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "2. Resize volumes",
     "bucketAggs": [
      {
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword:resize-volumes-* AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "3. Restart VMs",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword:restart-vms-* AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "4. Snapshot VMs",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword:snapshot-vms-* AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "5. Migrate VMs",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword:migrate-vms-* AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VMs/Data Volumes per iteration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Step 1: Create VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Avg VM ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Avg VM Ready Latency",
     "bucketAggs": [
      {
       "field": "vmiName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Avg Root DV ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Avg Root DV ready latency",
     "bucketAggs": [
      {
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\" AND dvName.keyword:*-root",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Avg Data DVs ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Average Data DVs ready latency",
     "bucketAggs": [
      {
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\" AND dvName.keyword:*-data-*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM provisioning lifecycle breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmiCreatedLatency", "id": "1", "type": "avg" },
      { "field": "vmiPendingLatency", "id": "3", "type": "avg" },
      { "field": "vmiSchedulingLatency", "id": "4", "type": "avg" },
      { "field": "vmiScheduledLatency", "id": "5", "type": "avg" },
      { "field": "vmiRunningLatency", "id": "6", "type": "avg" },
      { "field": "vmReadyLatency", "id": "7", "type": "avg" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "P${percentile} VM ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "vmiName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "P${percentile} Root DV ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DVReadyLatency",
     "bucketAggs": [
      {
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "settings": { "percents": [ "$percentile" ] }, "type": "percentiles" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\" AND dvName.keyword:*-root",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "P${percentile} Data DVs ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DVReadyLatency",
     "bucketAggs": [
      {
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "settings": { "percents": [ "$percentile" ] }, "type": "percentiles" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\" AND dvName.keyword:*-data-*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total end-to-end provisioning time (DV+VM) (Average)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"dvLatencyMeasurement\" AND dvName.keyword:*-root AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "VM Ready Latency",
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total end-to-end provisioning time (DV+VM) (Percentile $percentile)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "vmiName.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "dvName.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\" AND dvName.keyword:*-root",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Distribution of VMs per host",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "nodeName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM ready latency per host (Average)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "nodeName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM ready latency per host (Percentile $percentile)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "nodeName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "vmiName.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:create-vms-* AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Step 2: Resize volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Data Volume resize latency (Average)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "resizeLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:resize-volumes-* AND metricName.keyword:\"pvcLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Data Volume resize latency (Percentile $percentile)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "resizeLatency", "id": "1", "settings": { "percents": [ "$percentile" ] }, "type": "percentiles" }
     ],
     "query": "jobName.keyword:resize-volumes-* AND metricName.keyword:\"pvcLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Step 3: Restart VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Restart VMs execution duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 129 },
   "targets": [
    {
     "alias": "base",
     "bucketAggs": [
      {
       "field": "jobConfig.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword:restart-vms-* AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Step 4: Snapshot VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "Volume Snapshot ready latency (Average)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 138 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vsReadyLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:snapshot-vms-* AND metricName.keyword:\"volumeSnapshotLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Volume Snapshot ready latency (Percentile $percentile)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 146 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vsReadyLatency", "id": "1", "settings": { "percents": [ "$percentile" ] }, "type": "percentiles" }
     ],
     "query": "jobName.keyword:snapshot-vms-* AND metricName.keyword:\"volumeSnapshotLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Step 5: Migrate VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "VM migration ready latency (Average)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 155 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "succeededLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword: migrate-vms-* AND metricName.keyword:\"vmimLatencyMeasurement\" AND uuid: \"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM migration ready latency (Percentile $percentile)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 163 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "succeededLatency", "id": "1", "settings": { "percents": [ "$percentile" ] }, "type": "percentiles" }
     ],
     "query": "jobName.keyword: migrate-vms-* AND metricName.keyword:\"vmimLatencyMeasurement\" AND uuid: \"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM migration lifecycle breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 163 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "pendingLatency", "id": "1", "type": "avg" },
      { "field": "schedulingLatency", "id": "3", "type": "avg" },
      { "field": "scheduledLatency", "id": "4", "type": "avg" },
      { "field": "preparingTargetLatency", "id": "5", "type": "avg" },
      { "field": "targetReadyLatency", "id": "6", "type": "avg" },
      { "field": "runningLatency", "id": "7", "type": "avg" },
      { "field": "succeededLatency", "id": "8", "type": "avg" }
     ],
     "query": "jobName.keyword:migrate-vms-* AND metricName.keyword:\"vmimLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}