{
 "title": "kube-burner-virt-migration-benchmark",
 "time": { "from": "2017-07-23T03:05:06.532Z", "to": "2033-07-19T03:05:06.532Z" },
 "templating": {
  "list": [
   { "name": "DS_ELASTICSEARCH", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "uuid",
    "label": "Run UUID",
    "query": "{\"find\": \"terms\",\"field\": \"uuid.keyword\",\"query\": \"jobName.keyword:\\\"create-migrating-vms\\\"\"}"
   },
   { "name": "percentile", "label": "Latency Percentile", "query": "50, 90, 95, 99" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# **🚀 kube-burner-ocp virt migration benchmark dashboard**\n\nThis dashboard provides deep insights into the results of the virt-migration benchmark execution using kube-burner-ocp. For a deep dive into workload parameters and metric definitions, refer to the [official kube-burner-ocp documentation](https://kube-burner.github.io/kube-burner-ocp/latest/#virt-migration).\n\n### ⚙️ How to configure your view\n\nUse the dropdown selectors at the top of the dashboard to filter the results:\n\n- **Run UUID 🔽:** Select the unique identifier for your benchmark execution to filter all visualizations for that specific test run.\n- **Latency Percentile 📊:** Toggle between median (50th) for typical performance or tail latencies (90th/95th/99th) to identify worst-case bottlenecks in your infrastructure.\n\n📌 **NOTE:**\n- All latency metrics in this dashboard are reported in seconds.\n- Since the OS image is provisioned through persistent storage instead of being pulled directly into the `virt-launcher` pod’s local directory, this scenario results in the creation and binding of DataVolumes and PVCs."
   }
  },
  { "title": "Environment details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "OpenShift version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "OpenShift version",
     "bucketAggs": [
      {
       "field": "ocpVersion.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "metricName.keyword: \"jobSummary\" AND jobConfig.name.keyword: \"create-migrating-vms\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Control plane node count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "OpenShift version",
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "masterNodesCount", "id": "1", "type": "avg" }
     ],
     "query": "metricName.keyword: \"jobSummary\" AND jobConfig.name.keyword: \"create-migrating-vms\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Worker node count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "OpenShift version",
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "workerNodesCount", "id": "1", "type": "avg" }
     ],
     "query": "metricName.keyword: \"jobSummary\" AND jobConfig.name.keyword: \"create-migrating-vms\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Global performance overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Run details",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "metrics": [
      { "id": "4", "settings": { "limit": "1" }, "type": "logs" }
     ],
     "query": "jobConfig.name.keyword:\"create-migrating-vms\" AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total benchmark duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total execution duration",
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "sum" }
     ],
     "query": "metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Worker nodes to schedule and migrate from",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "nodeName.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "jobName.keyword:\"create-migrating-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total migrating VMs created",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmName.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "jobName.keyword:\"create-migrating-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Worker nodes hosting load VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "nodeName.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "jobName.keyword:\"create-load-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total load VMs created",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmName.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "jobName.keyword:\"create-load-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Average phase duration comparison",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "alias": "1. Start fresh",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword: \"start-fresh\" AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "2. Create migrating VMs",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword: \"create-migrating-vms\" AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "3. Create load VMs",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword: \"create-load-vms\" AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "4. Remove affinity rule",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword: \"remove-affinity-rule\" AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "5. Migrate VMs",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword: \"migrate-vms\" AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VMs/Data Volumes per iteration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "jobName.keyword:create-*-vms AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "jobName.keyword:create-*-vms AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Workload preparation - Create migrating VMs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 }
  },
  {
   "title": "Avg VM ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Avg VM Ready Latency",
     "bucketAggs": [
      {
       "field": "vmiName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-migrating-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Avg DV bound latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Avg DV Bound Latency",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "dvBoundLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-migrating-vms\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM provisioning lifecycle breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmiCreatedLatency", "id": "1", "type": "avg" },
      { "field": "vmiPendingLatency", "id": "3", "type": "avg" },
      { "field": "vmiSchedulingLatency", "id": "4", "type": "avg" },
      { "field": "vmiScheduledLatency", "id": "5", "type": "avg" },
      { "field": "vmiRunningLatency", "id": "6", "type": "avg" },
      { "field": "vmReadyLatency", "id": "7", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-migrating-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "P$percentile VM Ready Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "P$percentile VM Ready Latency",
     "bucketAggs": [
      {
       "field": "vmiName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-migrating-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "P$percentile DV Bound Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "P$percentile DV Bound Latency",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "dvBoundLatency", "id": "1", "settings": { "percents": [ "$percentile" ] }, "type": "percentiles" }
     ],
     "query": "jobName.keyword:\"create-migrating-vms\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total end-to-end provisioning time (DV+VM) (Average)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-migrating-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-migrating-vms\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total end-to-end provisioning time (DV+VM) (Percentile $percentile)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "vmiName.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-migrating-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "dvName.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-migrating-vms\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Workload preparation - Create load VMs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 }
  },
  {
   "title": "Avg VM ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Avg VM Ready Latency",
     "bucketAggs": [
      {
       "field": "vmiName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-load-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Avg DV bound latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Avg DV Bound Latency",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "dvBoundLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-load-vms\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM provisioning lifecycle breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmiCreatedLatency", "id": "1", "type": "avg" },
      { "field": "vmiPendingLatency", "id": "3", "type": "avg" },
      { "field": "vmiSchedulingLatency", "id": "4", "type": "avg" },
      { "field": "vmiScheduledLatency", "id": "5", "type": "avg" },
      { "field": "vmiRunningLatency", "id": "6", "type": "avg" },
      { "field": "vmReadyLatency", "id": "7", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-load-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "P$percentile VM ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "P$percentile VM Ready Latency",
     "bucketAggs": [
      {
       "field": "vmiName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-load-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "P$percentile DV Bound Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "P$percentile DV Bound Latency",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "dvBoundLatency", "id": "1", "settings": { "percents": [ "$percentile" ] }, "type": "percentiles" }
     ],
     "query": "jobName.keyword:\"create-load-vms\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total end-to-end provisioning time (DV+VM) (Average)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-load-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-load-vms\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total end-to-end provisioning time (DV+VM) (Percentile $percentile)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 111 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "vmiName.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-load-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "dvName.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-load-vms\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Infrastructure & Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Distribution of VMs per host",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 121 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "nodeName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "jobName.keyword:\"create-migrating-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "nodeName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "jobName.keyword:\"create-load-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM ready latency per host (Average)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 129 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "nodeName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "(jobName.keyword:\"create-migrating-vms\" OR jobName.keyword:\"create-load-vms\") AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM ready latency per host  (Percentile $percentile)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 137 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "nodeName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "vmiName.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "(jobName.keyword:\"create-migrating-vms\" OR jobName.keyword:\"create-load-vms\") AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Migrate VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 } },
  {
   "title": "Avg VM migration ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 146 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Avg VM Ready Latency",
     "bucketAggs": [
      {
       "field": "vmiName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "succeededLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:\"migrate-vms\" AND metricName.keyword:\"vmimLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "P$percentile VM migration ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 146 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "P$percentile VM migration Ready Latency",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "succeededLatency", "id": "1", "settings": { "percents": [ "$percentile" ] }, "type": "percentiles" }
     ],
     "query": "jobName.keyword:\"migrate-vms\" AND metricName.keyword:\"vmimLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM migration lifecycle breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 146 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "pendingLatency", "id": "1", "type": "avg" },
      { "field": "schedulingLatency", "id": "3", "type": "avg" },
      { "field": "scheduledLatency", "id": "4", "type": "avg" },
      { "field": "preparingTargetLatency", "id": "5", "type": "avg" },
      { "field": "targetReadyLatency", "id": "6", "type": "avg" },
      { "field": "runningLatency", "id": "7", "type": "avg" },
      { "field": "succeededLatency", "id": "8", "type": "avg" }
     ],
     "query": "jobName.keyword:migrate-vms AND metricName.keyword:\"vmimLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}