{
 "title": "kube-burner-virt-ephemeral-restart-benchmark",
 "time": { "from": "2017-07-23T03:05:06.532Z", "to": "2033-07-19T03:05:06.532Z" },
 "templating": {
  "list": [
   { "name": "DS_ELASTICSEARCH", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "uuid",
    "label": "Run UUID",
    "query": "{\"find\": \"terms\",\"field\": \"uuid.keyword\",\"query\": \"jobName.keyword:\\\"stop-ephemeral-vms\\\"\"}"
   },
   { "name": "percentile", "label": "Latency Percentile", "query": "50, 90, 95, 99" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# **🚀 kube-burner-ocp virt ephemeral restart benchmark dashboard**\n\nThis dashboard provides deep insights into the results of the virt-ephemeral-restart benchmark execution using kube-burner-ocp. For a deep dive into workload parameters and metric definitions, refer to the [official kube-burner-ocp documentation](https://kube-burner.github.io/kube-burner-ocp/latest/#virt-ephemeral-restart).\n\n### ⚙️ How to configure your view\n\nUse the dropdown selectors at the top of the dashboard to filter the results:\n\n- **Run UUID 🔽:** Select the unique identifier for your benchmark execution to filter all visualizations for that specific test run.\n- **Latency Percentile 📊:** Toggle between median (50th) for typical performance or tail latencies (90th/95th/99th) to identify worst-case bottlenecks in your infrastructure.\n\n📌 **NOTE:**\n- All latency metrics in this dashboard are reported in seconds.\n- Since the OS image is pulled directly into the `virt-launcher` pod’s local directory (typically on the node’s root disk), no DataVolumes or PVCs are created or bound for this scenario."
   }
  },
  { "title": "Environment details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "OpenShift version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ocpVersion.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "metricName.keyword: \"jobSummary\" AND jobConfig.name.keyword: \"stop-ephemeral-vms\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Control plane node count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "masterNodesCount", "id": "1", "type": "avg" }
     ],
     "query": "metricName.keyword: \"jobSummary\" AND jobConfig.name.keyword: \"stop-ephemeral-vms\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Worker node count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "workerNodesCount", "id": "1", "type": "avg" }
     ],
     "query": "metricName.keyword: \"jobSummary\" AND jobConfig.name.keyword: \"stop-ephemeral-vms\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Global performance overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Run details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "metrics": [
      { "id": "4", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "jobConfig.name.keyword:\"stop-ephemeral-vms\" AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total benchmark duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total execution duration",
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "sum" }
     ],
     "query": "metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Iterations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "jobIteration", "id": "1", "type": "max" }
     ],
     "query": "jobName:\"create-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Worker nodes in use",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "nodeName.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "jobName.keyword:\"create-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total VMs created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmName.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "jobName.keyword:\"create-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Average phase duration comparison",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "alias": "1. Start fresh",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword: \"start-fresh\" AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "2. Create base image DV",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword: \"create-base-image-dv\" AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "3. Create data source",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword: \"create-data-source\" AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "4. Create VMs",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword: \"create-vms\" AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "5. Stop ephemeral VMs",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword: \"stop-ephemeral-vms\" AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "6. Start VMs",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword: \"start-vms\" AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "7. Delete ephemeral volumes",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword: delete-ephemeral-volumes-* AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "8. Start ephemeral VMs",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword: start-ephemeral-vms-* AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "alias": "9. Wait running",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsedTime", "id": "1", "type": "avg" }
     ],
     "query": "jobConfig.name.keyword: \"wait-running\" AND metricName.keyword:\"jobSummary\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Workload preparation - Create base image DV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "DV running latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DV Running Latency",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "dvRunningLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-base-image-dv\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "DV bound latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DV Bound Latency",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "dvBoundLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-base-image-dv\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "DV ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DV Ready Latency",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-base-image-dv\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Workload preparation - Create VMs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }
  },
  {
   "title": "Avg VM ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "vmReadyLatency",
     "bucketAggs": [
      {
       "field": "vmiName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Avg DV ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Avg DV Ready Latency",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-vms\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM provisioning lifecycle breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmiCreatedLatency", "id": "1", "type": "avg" },
      { "field": "vmiPendingLatency", "id": "3", "type": "avg" },
      { "field": "vmiSchedulingLatency", "id": "4", "type": "avg" },
      { "field": "vmiScheduledLatency", "id": "5", "type": "avg" },
      { "field": "vmiRunningLatency", "id": "6", "type": "avg" },
      { "field": "vmReadyLatency", "id": "7", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "P${percentile} VM ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "P$percentile VM Ready Latency",
     "bucketAggs": [
      {
       "field": "vmiName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "P$percentile DV ready latency (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "P$percentile DV Ready Latency",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "settings": { "percents": [ "$percentile" ] }, "type": "percentiles" }
     ],
     "query": "jobName.keyword:\"create-vms\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total End-to-End provisioning time (DV+VM)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-vms\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total end-to-end provisioning time (DV+VM) (Percentile $percentile)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "vmiName.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "dvName.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-vms\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Distribution of VMs per host",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "nodeName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "jobName.keyword:\"create-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM ready latency per host (Average)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "nodeName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM ready latency per host (Percentile $percentile)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "nodeName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "vmiName.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"create-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Restart ephemeral VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "VM ready latency (Average)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"start-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:\"start-vms\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM ready latency per host (Percentile $percentile)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "vmiName.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"start-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "jobIteration",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "dvName.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "dvReadyLatency", "id": "1", "type": "avg" }
     ],
     "query": "jobName.keyword:\"start-vms\" AND metricName.keyword:\"dvLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Distribution of VMs per host",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "nodeName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "jobName.keyword:\"start-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM ready latency per host (Average)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "nodeName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"start-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM ready latency per host (Percentile $percentile)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "nodeName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "vmiName.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "vmReadyLatency", "id": "1", "type": "avg" },
      { "field": "vmiCreatedLatency", "id": "3", "type": "avg" }
     ],
     "query": "jobName.keyword:\"start-vms\" AND metricName.keyword:\"vmiLatencyMeasurement\" AND uuid:\"$uuid\"",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}