{
 "title": "Kube-burner report mode",
 "tags": [ "kube-burner" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "platform",
    "label": "Platform",
    "query": "{\"find\": \"terms\", \"field\": \"platform.keyword\"}"
   },
   {
    "name": "sdn",
    "label": "SDN type",
    "query": "{\"find\": \"terms\", \"field\": \"sdnType.keyword\", \"query\": \"platform.keyword: $platform\"}"
   },
   {
    "name": "clusterType",
    "label": "clusterType",
    "query": "{\"find\": \"terms\", \"field\": \"clusterType.keyword\", \"query\": \"platform.keyword: $platform\"}"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "{\"find\": \"terms\", \"field\": \"jobConfig.name.keyword\", \"query\": \"platform.keyword: $platform AND sdnType.keyword: $sdn AND clusterType.keyword: $clusterType AND NOT jobConfig.name: garbage-collection\"}"
   },
   {
    "name": "workerNodesCount",
    "label": "Workers",
    "query": "{\"find\": \"terms\", \"field\": \"workerNodesCount\", \"query\": \"platform.keyword: $platform AND sdnType.keyword: $sdn AND jobConfig.name.keyword: $job AND clusterType.keyword: $clusterType\"}"
   },
   {
    "name": "ocpMajorVersion",
    "label": "OCP Major",
    "query": "{\"find\": \"terms\", \"field\": \"ocpMajorVersion.keyword\", \"query\": \"platform.keyword: $platform AND sdnType.keyword: $sdn AND jobConfig.name.keyword: $job AND workerNodesCount: $workerNodesCount AND clusterType.keyword: $clusterType\"}"
   },
   {
    "name": "uuid",
    "label": "UUID",
    "query": "{\"find\": \"terms\", \"field\": \"uuid.keyword\", \"query\": \"platform.keyword: $platform AND sdnType.keyword: $sdn AND jobConfig.name.keyword: $job AND workerNodesCount: $workerNodesCount  AND ocpMajorVersion.keyword: $ocpMajorVersion AND clusterType.keyword: $clusterType\"}"
   },
   {
    "name": "compare_by",
    "label": "Compare by",
    "query": "uuid,metadata.ocpVersion,metadata.ocpMajorVersion"
   },
   {
    "name": "component",
    "label": "Component",
    "query": "crio,kube-apiserver,kube-controller-manager,kubelet,multus,openshift-apiserver,openshift-controller-manager,ovn-control-plane,ovnkube-node,prometheus,router"
   },
   { "name": "node_roles", "label": "Node roles", "query": "masters,workers,infra" },
   { "name": "Filter" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: jobSummary",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: jobSummary",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Node Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "$workerNodesCount nodes - CPU usage $node_roles",
     "type": "bargauge",
     "description": "Average CPU usage across nodes",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
     "repeat": "node_roles",
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: cpu-$node_roles",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Maximum CPU usage $node_roles",
     "type": "bargauge",
     "description": "Maximum CPU usage across nodes",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 16 },
     "repeat": "node_roles",
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: max-cpu-$node_roles",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$workerNodesCount nodes - Memory usage $node_roles",
     "type": "bargauge",
     "description": "Average memory usage across nodes",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 20 },
     "repeat": "node_roles",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: memory-$node_roles",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$workerNodesCount nodes - Maximum aggregated memory usage $node_roles",
     "type": "bargauge",
     "description": "Maximum aggregated memory usage across nodes",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 24 },
     "repeat": "node_roles",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: max-memory-sum-$node_roles",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Max Cluster CPU usage ratio",
     "type": "barchart",
     "description": "Maximum usage ratio, based on\ncluster:node_cpu:ratio\nRatio is calculated from capacity/usage",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "alias": "Memory",
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: max-cpu-cluster-usage-ratio",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Max Cluster memory usage ratio",
     "type": "barchart",
     "description": "Maximum usage ratio, based on\ncluster:memory_usage:ratio\nRatio is calculated from capacity/usage",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "alias": "Memory",
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: max-memory-cluster-usage-ratio",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod & Service ready latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "$workerNodesCount nodes - P99 Pod ready latency",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "P99", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: podLatencyQuantilesMeasurement AND quantileName.keyword: Ready",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$workerNodesCount nodes - P99 Service ready latency",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "P99", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: svcLatencyQuantilesMeasurement AND quantileName.keyword: Ready",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "API latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Only API request P99 latency - resource scoped",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "Memory",
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: avg-ro-apicalls-latency  AND labels.scope.keyword: resource",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Maximum Read Only API request P99 latency - resource scoped",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "Memory",
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: max-ro-apicalls-latency AND labels.scope.keyword: resource",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Read Only API request P99 latency - namespace scoped",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "Memory",
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: avg-ro-apicalls-latency AND labels.scope.keyword: namespace",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Maximum Read Only API request P99 latency - namespace scoped",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "Memory",
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: max-ro-apicalls-latency AND labels.scope.keyword: namespace",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Read Only API request P99 latency - cluster scoped",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "Memory",
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: avg-ro-apicalls-latency ",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Maximum Read Only API request P99 latency - cluster scoped",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "Memory",
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: max-ro-apicalls-latency AND labels.scope.keyword: cluster",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Mutating API request P99 latency",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "Memory",
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: avg-mutating-apicalls-latency",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Maximum Mutating API request P99 latency",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "Memory",
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: max-mutating-apicalls-latency",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Etcd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "99th WAL fsync ",
     "type": "barchart",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: 99thEtcdDiskWalFsync",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Maximum 99th WAL fsync ",
     "type": "barchart",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: max-99thEtcdDiskWalFsync",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "99th Roundtrip",
     "type": "barchart",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: 99thEtcdRoundTripTime",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Maximum 99th Roundtrip",
     "type": "barchart",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: max-99thEtcdRoundTripTime",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "99th Backend I/O",
     "type": "barchart",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: 99thEtcdDiskBackendCommit",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Maximum 99th Backend I/O",
     "type": "barchart",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: max-99thEtcdDiskBackendCommit",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Etcd CPU usage",
     "type": "bargauge",
     "description": "Average CPU usage across the aggregated replicas",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: cpu-etcd",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Maximum Etcd CPU usage",
     "type": "bargauge",
     "description": "Maximum CPU usage across replicas",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: max-cpu-etcd",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Etcd RSS usage",
     "type": "bargauge",
     "description": "Average RSS usage across the aggregated replicas",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: memory-etcd",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Etcd max RSS usage",
     "type": "bargauge",
     "description": "Max RSS usage across all replicas",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "$compare_by.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "value", "id": "1", "type": "avg" }
       ],
       "query": "uuid.keyword: $uuid AND metricName.keyword: max-memory-etcd",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  { "title": "$component", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "component" },
  {
   "title": "Average RSS Usage $component",
   "type": "barchart",
   "description": "Average RSS across all replicas",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "RSS",
     "bucketAggs": [
      {
       "field": "$compare_by.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: memory-${component:raw}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Maximum CPU Usage $component",
   "type": "barchart",
   "description": "Maximum CPU across all replicas",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "alias": "RSS",
     "bucketAggs": [
      {
       "field": "$compare_by.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: max-cpu-${component:raw}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Max RSS Usage $component",
   "type": "barchart",
   "description": "Max RSS across all replicas",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "RSS",
     "bucketAggs": [
      {
       "field": "$compare_by.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: max-memory-${component:raw}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Average CPU Usage $component",
   "type": "barchart",
   "description": "Average CPU across all replicas",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "alias": "RSS",
     "bucketAggs": [
      {
       "field": "$compare_by.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: cpu-${component:raw}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Max Aggregated RSS Usage $component",
   "type": "barchart",
   "description": "Max aggregated memory usage seen in all replicas",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "RSS",
     "bucketAggs": [
      {
       "field": "$compare_by.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: max-memory-sum-${component:raw}",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}