---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{.dvNamePrefix}}-{{default 0 .Iteration}}
  annotations:
    cdi.kubevirt.io/storage.deleteAfterCompletion: "false"
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
{{- if .perNodeDV }}
    volume.kubernetes.io/selected-node: {{if .Iteration}}{{index (splitList " " .workerNodes) .Iteration}}{{else}}{{index (splitList " " .workerNodes) 0}}{{end}}
{{- end }}
spec:
  source:
{{- if eq (index . "cdiSourceType") "s3" }}
    s3:
      url: "{{.windowsImageURL}}"
{{- if (index . "cdiSourceS3Cred") }}
      secretRef: {{.cdiSourceS3Cred}}
{{- end }}
{{- else }}
    http:
      url: "{{.windowsImageURL}}"
{{- end }}
  storage:
    accessModes:
    - {{.accessMode}}
    volumeMode: Block
    resources:
      requests:
        storage: {{.storageSize}}
    storageClassName: {{.storageClassName}}
