kind: Deployment
apiVersion: apps/v1
metadata:
  name: anp-db-{{.Iteration}}-{{.Replica}}
spec:
  template:
    metadata:
      labels:
        name: postgres-{{.Iteration}}-{{.Replica}} 
        type: perfdb-{{.Iteration}}-{{.Replica}}
        trafficapp: "perfdb"
        tenant: {{.tenant}}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
              - key: node-role.kubernetes.io/workload
                operator: DoesNotExist    
      containers:
      - name: postgresql
        image: registry.redhat.io/rhel8/postgresql-10@sha256:4b912c80085b88a03309aeb7907efcc29dd3342fa3952b6ea067afb1914bfe53
        readinessProbe:
          tcpSocket:
            port: 5432
          periodSeconds: 10
          failureThreshold: 1
          timeoutSeconds: 10
          initialDelaySeconds: 3
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRESQL_USER
          value: admin
        - name: POSTGRESQL_PASSWORD
          value: secret
        - name: POSTGRESQL_DATABASE
          value: node-density
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        resources:
          requests:
            memory: "20Mi"
            cpu: "20m"
      restartPolicy: Always
  replicas: {{.podReplicas}}  
  selector:
    matchLabels:
      name: postgres-{{.Iteration}}-{{.Replica}}
  strategy:
    type: RollingUpdate
