apiVersion: olm.operatorframework.io/v1
kind: BundleUnpack
metadata:
  name: {{ .NAME_PREFIX }}-{{ .Iteration }}
spec:
  bundlePath: registry.redhat.io/redhat/redhat-operator-index:{{ .Version }}
  catalogSourceRef:
    name: benchmark-cc{{ .Iteration }}
    kind: ClusterCatalog
  package: test-package
  channel: stable
  targetNamespaces:
    - olmv1
