apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: "ce-{{.Iteration}}"
spec:
  namespace: "{{.prefixNamespace}}"
  serviceAccount:
    name: "ins-sa-{{.Iteration}}"
  source:
    sourceType: Catalog
    catalog:
      packageName: "{{.prefixPkgName}}{{.Iteration}}"
