apiVersion: v1
kind: Namespace
metadata:
  name: udn-bgp-{{.Iteration}}
  labels:
    security.openshift.io/scc.podSecurityLabelSync: "false"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    k8s.ovn.org/primary-user-defined-network: ""
    cluster-udn: cudn-{{.Iteration}}
