---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  deletionStrategy: {{.DELETION_STRATEGY}}
{{ if .PPROF }}
  measurements:
    - name: pprof
      pprofInterval: {{.PPROF_INTERVAL}}
      pprofDirectory: pprof-data
      pprofTargets:
      - name: ovnkube-controller-heap
        namespace: "openshift-ovn-kubernetes"
        labelSelector: {app: ovnkube-node}
        url: http://localhost:29103/debug/pprof/heap
      - name: ovnkube-controller-cpu
        namespace: "openshift-ovn-kubernetes"
        labelSelector: {app: ovnkube-node}
        url: http://localhost:29103/debug/pprof/profile?seconds=60
      - name: ovnk-control-plane-heap
        namespace: "openshift-ovn-kubernetes"
        labelSelector: {app: ovnkube-control-plane}
        url: http://localhost:29108/debug/pprof/heap
      - name: ovnk-control-plane-cpu
        namespace: "openshift-ovn-kubernetes"
        labelSelector: {app: ovnkube-control-plane}
        url: http://localhost:29108/debug/pprof/profile?seconds=60
{{ end }}
metricsEndpoints:
{{ if .ES_SERVER }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      esServers: ["{{.ES_SERVER}}"]
      insecureSkipVerify: true
      defaultIndex: {{.ES_INDEX}}
      type: opensearch
{{ end }}
{{ if .LOCAL_INDEXING }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      type: local
      metricsDirectory: collected-metrics-{{.UUID}}
{{ end }}

jobs:
{{ if .OCPBUGS_85627_WORKAROUND }}
  - name: cudn-density-workaround
    namespace: redhat-ocpbugs-85627-wa
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: false
    preCreateNamespaces: true
    waitWhenFinished: true
    skipIndexing: true
    cleanup: false
    jobPause: 1m
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:
      - objectTemplate: workaround-sa.yml
        replicas: 1

      - objectTemplate: workaround-rolebinding.yml
        replicas: 1

      - objectTemplate: workaround-secret.yml
        replicas: 1

      - objectTemplate: workaround-daemonset.yml
        replicas: 1
{{ end }}

  - name: cudn-density
    namespace: cudn-density
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    preCreateNamespaces: true
    waitWhenFinished: true
    preLoadImages: true
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
      k8s.ovn.org/primary-user-defined-network: ""
    measurements:
      - name: cudnLatency
      - name: podLatency
{{ if ne .POD_READY_THRESHOLD 0 }}
        thresholds:
          - conditionType: Ready
            metric: P99
            threshold: {{.POD_READY_THRESHOLD}}
{{ end }}
    churnConfig:
      cycles: {{.CHURN_CYCLES}}
      duration: {{.CHURN_DURATION}}
      percent: {{.CHURN_PERCENT}}
      delay: {{.CHURN_DELAY}}
      mode: {{.CHURN_MODE}}
{{ if ne .INCREMENTAL_STEP_SIZE 0 }}
    incrementalLoad:
      startIterations: {{.INCREMENTAL_STEP_SIZE}}
      totalIterations: {{.JOB_ITERATIONS}}
      stepDelay: {{.INCREMENTAL_STEP_DELAY}}
      pattern:
        type: {{.INCREMENTAL_PATTERN}}
{{ if eq .INCREMENTAL_PATTERN "linear" }}
        linear:
          stepSize: {{.INCREMENTAL_STEP_SIZE}}
{{ else }}
        exponential:
          base: {{.INCREMENTAL_EXP_BASE}}
{{ end }}
{{ end }}
{{ if .HTTP_SERVER_ADDRESS }}
    hooks:
      - cmd: ["./cudn_nginx.sh", "setup", "{{.HTTP_SERVER_ADDRESS}}"]
        when: beforeJobExecution
      - cmd: ["./cudn_nginx.sh", "cleanup"]
        when: afterJobExecution
{{ end }}
    jobPause: {{.JOB_PAUSE}}
    metricsClosing: afterJobPause
    cleanup: false
    objects:
      {{ if .ENABLE_LAYER_3 }}
      - objectTemplate: cudn-l3.yml
        replicas: 1
        churn: false
        group:
          id: 1
          pauseBeforeGC: {{.JOB_PAUSE}}
        repeatEveryNIterations: {{.NAMESPACES_PER_CUDN}}
        inputVars:
          namespaces_per_cudn: {{.NAMESPACES_PER_CUDN}}
          total_namespaces: {{.JOB_ITERATIONS}}
          cudns_per_ra: {{.CUDNS_PER_RA}}
        waitOptions:
          customStatusPaths:
            - key: .conditions[] | select(.type=="NetworkAllocationSucceeded") | .status
              value: "True"
      {{ else }}
      - objectTemplate: cudn-l2.yml
        replicas: 1
        churn: false
        group:
          id: 1
          pauseBeforeGC: {{.JOB_PAUSE}}
        repeatEveryNIterations: {{.NAMESPACES_PER_CUDN}}
        inputVars:
          namespaces_per_cudn: {{.NAMESPACES_PER_CUDN}}
          total_namespaces: {{.JOB_ITERATIONS}}
          cudns_per_ra: {{.CUDNS_PER_RA}}
        waitOptions:
          customStatusPaths:
            - key: .conditions[] | select(.type=="NetworkAllocationSucceeded") | .status
              value: "True"
      {{ end }}
      {{ if .BGP }}
      - objectTemplate: ra.yml
        replicas: 1
        churn: false
        group:
          id: 0
        repeatEveryNIterations: {{mul .NAMESPACES_PER_CUDN .CUDNS_PER_RA}}
      {{ end }}

      - objectTemplate: configmap.yml
        replicas: 1
        churn: false
        group:
          id: 2

      - objectTemplate: service.yml
        replicas: 1
        churn: false
        group:
          id: 2

      - objectTemplate: service-headless.yml
        replicas: 1
        churn: false
        group:
          id: 2

      - objectTemplate: service-server.yml
        replicas: 1
        churn: false
        group:
          id: 2

      - objectTemplate: np-deny-all.yml
        replicas: 1
        churn: false
        group:
          id: 2

      - objectTemplate: np-allow-cudn-ingress.yml
        replicas: 1
        churn: false
        group:
          id: 2
        inputVars:
          namespaces_per_cudn: {{.NAMESPACES_PER_CUDN}}

      - objectTemplate: np-allow-cudn-egress.yml
        replicas: 1
        churn: false
        group:
          id: 2
        inputVars:
          namespaces_per_cudn: {{.NAMESPACES_PER_CUDN}}


      - objectTemplate: np-allow-app-ingress.yml
        replicas: 1
        churn: false
        group:
          id: 2
        inputVars:
          namespaces_per_cudn: {{.NAMESPACES_PER_CUDN}}

      - objectTemplate: np-allow-app-egress.yml
        replicas: 1
        churn: false
        group:
          id: 2
        inputVars:
          namespaces_per_cudn: {{.NAMESPACES_PER_CUDN}}
          {{ if .HTTP_SERVER_ADDRESS }}
          httpServerIP: "{{.HTTP_SERVER_IP}}"
          httpServerPort: "{{.HTTP_SERVER_PORT}}"
          {{ end }}

      - objectTemplate: egressfirewall.yml
        replicas: 1
        churn: false
        group:
          id: 2
        inputVars:
          nodeGwMap: '{{ if .GATEWAY_CHECK }}{{.NODE_GW_MAP}}{{ end }}'
          {{ if .HTTP_SERVER_ADDRESS }}
          httpServerIP: "{{.HTTP_SERVER_IP}}"
          {{ end }}

      - objectTemplate: resourcequota.yml
        replicas: 1
        churn: false
        group:
          id: 2

      - objectTemplate: limitrange.yml
        replicas: 1
        churn: false
        group:
          id: 2

{{ if .GATEWAY_CHECK }}
      - objectTemplate: np-allow-gateway-egress.yml
        replicas: 1
        churn: false
        group:
          id: 2
        inputVars:
          nodeGwMap: '{{.NODE_GW_MAP}}'
{{ end }}

      - objectTemplate: deployment-server.yml
        replicas: 1
        group:
          id: 2
        inputVars:
          podReplicas: 2

      - objectTemplate: deployment-app.yml
        replicas: 1
        group:
          id: 2
        inputVars:
          podReplicas: 1
          httpServerAddress: "{{.HTTP_SERVER_ADDRESS}}"

      - objectTemplate: deployment-client.yml
        replicas: 1
        group:
          id: 2
        inputVars:
          podReplicas: 1
          namespaces_per_cudn: {{.NAMESPACES_PER_CUDN}}
          gatewayCheck: {{.GATEWAY_CHECK}}
          nodeGwMap: '{{ if .GATEWAY_CHECK }}{{.NODE_GW_MAP}}{{ end }}'

{{ if .GC }}
  - name: cudn-density-cleanup-namespaces
    jobType: delete
    waitForDeletion: false
    qps: {{.QPS}}
    burst: {{.BURST}}
    skipIndexing: true
    objects:
      - kind: Namespace
        apiVersion: v1
        labelSelector: {kube-burner.io/job: cudn-density}

  - name: cudn-density-cleanup-cudns
    jobType: delete
    waitForDeletion: true
    qps: {{.QPS}}
    burst: {{.BURST}}
    skipIndexing: true
    objects:
      {{ if .BGP }}
      - kind: RouteAdvertisements
        apiVersion: k8s.ovn.org/v1
        labelSelector: {kube-burner.io/job: cudn-density}
      {{ end }}
      - kind: ClusterUserDefinedNetwork
        apiVersion: k8s.ovn.org/v1
        labelSelector: {kube-burner.io/job: cudn-density}

{{ if .OCPBUGS_85627_WORKAROUND }}
  - name: cudn-density-cleanup-workaround
    jobType: delete
    waitForDeletion: true
    qps: 20
    burst: 20
    skipIndexing: true
    objects:
      - kind: Namespace
        apiVersion: v1
        labelSelector: {kube-burner.io/job: cudn-density-workaround}
{{ end }}
{{ end }}
