---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
{{ if .PPROF }}
  measurements:
    - name: pprof
      pprofInterval: {{.PPROF_INTERVAL}}
      pprofDirectory: pprof-data
      pprofTargets:
      - name: ovnkube-controller-heap
        namespace: "openshift-ovn-kubernetes"
        labelSelector: {app: ovnkube-node}
        url: http://localhost:29103/debug/pprof/heap
      - name: ovnkube-controller-cpu
        namespace: "openshift-ovn-kubernetes"
        labelSelector: {app: ovnkube-node}
        url: http://localhost:29103/debug/pprof/profile?seconds=60
      - name: ovnk-control-plane-heap
        namespace: "openshift-ovn-kubernetes"
        labelSelector: {app: ovnkube-control-plane}
        url: http://localhost:29108/debug/pprof/heap
      - name: ovnk-control-plane-cpu
        namespace: "openshift-ovn-kubernetes"
        labelSelector: {app: ovnkube-control-plane}
        url: http://localhost:29108/debug/pprof/profile?seconds=60
{{ end }}
metricsEndpoints:
{{ if .ES_SERVER }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      esServers: ["{{.ES_SERVER}}"]
      insecureSkipVerify: true
      defaultIndex: {{.ES_INDEX}}
      type: opensearch
{{ end }}
{{ if .LOCAL_INDEXING }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      type: local
      metricsDirectory: collected-metrics-{{.UUID}}
{{ end }}

jobs:
  - name: cudn-density-cudn-churn
    namespace: cudn-density
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    preCreateNamespaces: true
    waitWhenFinished: true
    preLoadImages: true
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
      k8s.ovn.org/primary-user-defined-network: ""
    measurements:
      - name: cudnLatency
      - name: podLatency
{{ if ne .POD_READY_THRESHOLD 0 }}
        thresholds:
          - conditionType: Ready
            metric: P99
            threshold: {{.POD_READY_THRESHOLD}}
{{ end }}
    churnConfig:
      cycles: {{.CHURN_CYCLES}}
      duration: {{.CHURN_DURATION}}
      percent: {{.CHURN_PERCENT}}
      delay: {{.CHURN_DELAY}}
      mode: {{.CHURN_MODE}}
    jobPause: 2m
    metricsClosing: afterJobPause
    cleanup: false
    objects:
      {{ if .ENABLE_LAYER_3 }}
      - objectTemplate: cudn-l3.yml
        replicas: 1
        group:
          id: 1
        repeatEveryNIterations: {{.NAMESPACES_PER_CUDN}}
        inputVars:
          namespaces_per_cudn: {{.NAMESPACES_PER_CUDN}}
          total_namespaces: {{.JOB_ITERATIONS}}
        waitOptions:
          customStatusPaths:
            - key: .conditions[] | select(.type=="NetworkAllocationSucceeded") | .status
              value: "True"
      {{ else }}
      - objectTemplate: cudn-l2.yml
        replicas: 1
        group:
          id: 1
        repeatEveryNIterations: {{.NAMESPACES_PER_CUDN}}
        inputVars:
          namespaces_per_cudn: {{.NAMESPACES_PER_CUDN}}
          total_namespaces: {{.JOB_ITERATIONS}}
        waitOptions:
          customStatusPaths:
            - key: .conditions[] | select(.type=="NetworkAllocationSucceeded") | .status
              value: "True"
      {{ end }}

      - objectTemplate: configmap.yml
        replicas: 1
        group:
          id: 2

      - objectTemplate: service.yml
        replicas: 1
        group:
          id: 2

      - objectTemplate: service-headless.yml
        replicas: 1
        group:
          id: 2

      - objectTemplate: service-server.yml
        replicas: 1
        group:
          id: 2

      - objectTemplate: np-deny-all.yml
        replicas: 1
        group:
          id: 2

      - objectTemplate: np-allow-cudn-ingress.yml
        replicas: 1
        group:
          id: 2
        inputVars:
          namespaces_per_cudn: {{.NAMESPACES_PER_CUDN}}

      - objectTemplate: np-allow-cudn-egress.yml
        replicas: 1
        group:
          id: 2
        inputVars:
          namespaces_per_cudn: {{.NAMESPACES_PER_CUDN}}

      - objectTemplate: np-allow-app-ingress.yml
        replicas: 1
        group:
          id: 2
        inputVars:
          namespaces_per_cudn: {{.NAMESPACES_PER_CUDN}}

      - objectTemplate: np-allow-app-egress.yml
        replicas: 1
        group:
          id: 2
        inputVars:
          namespaces_per_cudn: {{.NAMESPACES_PER_CUDN}}

      - objectTemplate: egressfirewall.yml
        replicas: 1
        group:
          id: 2

      - objectTemplate: resourcequota.yml
        replicas: 1
        group:
          id: 2

      - objectTemplate: limitrange.yml
        replicas: 1
        group:
          id: 2

      - objectTemplate: deployment-server.yml
        replicas: 1
        group:
          id: 2
        inputVars:
          podReplicas: 2

      - objectTemplate: deployment-app.yml
        replicas: 1
        group:
          id: 2
        inputVars:
          podReplicas: 1

      - objectTemplate: deployment-client.yml
        replicas: 1
        group:
          id: 2
        inputVars:
          podReplicas: 1
          namespaces_per_cudn: {{.NAMESPACES_PER_CUDN}}

{{ if .GC }}
  - name: cudn-density-cudn-churn-cleanup-namespaces
    jobType: delete
    waitForDeletion: false
    qps: {{.QPS}}
    burst: {{.BURST}}
    skipIndexing: true
    objects:
      - kind: Namespace
        apiVersion: v1
        labelSelector: {kube-burner.io/job: cudn-density-cudn-churn}

  - name: cudn-density-cudn-churn-cleanup-cudns
    jobType: delete
    waitForDeletion: true
    qps: {{.QPS}}
    burst: {{.BURST}}
    skipIndexing: true
    objects:
      - kind: ClusterUserDefinedNetwork
        apiVersion: k8s.ovn.org/v1
        labelSelector: {kube-burner.io/job: cudn-density-cudn-churn}
{{ end }}
