---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway-checker-{{.Replica}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cudn-density-gateway-checker-{{.Replica}}
  template:
    metadata:
      labels:
        name: cudn-density-gateway-checker-{{.Replica}}
        app: gateway-checker
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: gateway-checker
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
              - key: node-role.kubernetes.io/workload
                operator: DoesNotExist
      containers:
      - name: gateway-checker
        image: quay.io/cloud-bulldozer/curl:latest
        env:
        - name: GATEWAY_IP
          value: "{{.gatewayIP}}"
        - name: EXTERNAL_IP
          value: "8.8.8.8"
        command:
          - "/bin/sh"
          - "-c"
          - "while true; do echo ping on ${EXTERNAL_IP}; ping -c 1 -W 3 ${EXTERNAL_IP}; sleep 120; done"
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        readinessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "if [ ! -f /tmp/ready.log ]; then ping -c 1 -W 3 ${GATEWAY_IP} && ping -c 1 -W 3 ${EXTERNAL_IP} && touch /tmp/ready.log; else ping -c 1 -W 3 ${GATEWAY_IP}; fi"
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always
  strategy:
    type: RollingUpdate
