apiVersion: v1
kind: Secret
metadata:
  name: redhat-ocpbugs-85627-script
type: Opaque
stringData:
  redhat-ocpbugs-85627-script.sh: |
    #!/bin/bash

    ## This script is maintained by Red Hat OpenShift support
    ## For the unique scope to workaround https://redhat.atlassian.net/browse/OCPBUGS-85627

    ## This script is executed in a privileged pod which mounts the root of the node under /host
    ## The goal is to inject static MAC bindings for all the known hosts in the L2 network
    ## The bindings are added into all rtoe ports of every OVN GatewayRouter
    ## Execution:
    ## 1) identify default router and its MAC address, must be on br-ex
    ## 2) verify a static mac binding for the default router exists if not create it
    ## 3) identify all the known hosts in the same L2 network and create the binding if not exist
    ## 4) execute a final verification

    RUNCRICTL="chroot /host /usr/bin/crictl"
    NORTHDC=$(${RUNCRICTL} ps --name northd --state Running -q 2>/dev/null)
    EXECC="${RUNCRICTL} exec ${NORTHDC}"

    REVERT="${1:-false}"

    if [[ ${NORTHDC} == "" ]] ;then
      echo "$(date +%FT%T.%Z) ERROR: Impossible to continue: Northd container is not running."
      exit 1
    fi

    nodehostname=$(${EXECC} uname -n)
    GR="GR_${nodehostname}"

    if [[ -z ${nodehostname} ]];then
      echo "$(date +%FT%T.%Z) ERROR: Impossible to continue: Something is wrong while executing uname commands in the northd container."
      exit 1
    fi

    routerIP=$(${EXECC} ip route list dev br-ex default |cut -d' ' -f3)
    routerMAC=$(${EXECC} ip neigh get ${routerIP} dev br-ex |cut -d' ' -f5)

    if [[ -z ${routerIP} ]] || [[ -z ${routerMAC} ]];then
      echo "$(date +%FT%T.%Z) ERROR: Impossible to continue: Something is wrong while executing ip commands in the northd container."
      exit 1
    fi

    LRPORTS=$(${EXECC} ovn-nbctl --columns=name --bare find logical_router_port | grep rtoe-GR)

    COUNT=1

    for port in ${LRPORTS} ; do
      ${EXECC} ovn-nbctl --bare --columns=mac find static_mac_binding logical_port=${port} ip=${routerIP} |grep -q ${routerMAC}
      if [[ $? -gt 0 ]] && [[ ${REVERT} != "revert" ]]; then
        echo "$(date +%FT%T.%Z) CHANGING: Add Mac binding to port ${port} for ${routerIP} because not present."
        ${EXECC} ovn-nbctl --may-exist --wait=sb static-mac-binding-add ${port} ${routerIP} ${routerMAC}
      elif [[ ${REVERT} == "revert" ]] && [[ $(${EXECC} ovn-nbctl --bare --columns=ip find static_mac_binding logical_port=${port} ip=${routerIP} |grep ${routerIP} |wc -l) -gt 0 ]];then
        echo "$(date +%FT%T.%Z) REVERTING: removing static-mac-binding from port ${port} for ${routerIP}"
        ${EXECC} ovn-nbctl --wait=sb --if-exists static-mac-binding-del ${port} ${routerIP}
      fi
    done

    NEIGHBORS=$(${EXECC} ip neigh show $(${EXECC} ip -f inet -br a s br-ex |awk '{print $3}') |grep -v ${routerIP} |grep -v "FAILED" |awk '{print $1" "$5}')

    while read ip mac ; do
      for port in ${LRPORTS} ; do
        ${EXECC} ovn-nbctl --bare --columns=mac find static_mac_binding logical_port=${port} ip=${ip} |grep -q ${mac}
        if [[ $? -gt 0 ]] && [[ ${REVERT} != "revert" ]]; then
          echo "$(date +%FT%T.%Z) CHANGING: Add Mac binding to port ${port} for ${ip} because not present."
          ${EXECC} ovn-nbctl --may-exist --wait=sb static-mac-binding-add ${port} ${ip} ${mac}
        elif [[ ${REVERT} == "revert" ]] && [[ $(${EXECC} ovn-nbctl --bare --columns=ip find static_mac_binding logical_port=${port} ip=${ip} |grep ${ip} |wc -l) -gt 0 ]];then
          echo "$(date +%FT%T.%Z) REVERTING: removing static-mac-binding from port ${port} for ${ip}"
          ${EXECC} ovn-nbctl --wait=sb --if-exists static-mac-binding-del ${port} ${ip}
        fi
      done
    done <<< "${NEIGHBORS}"

    ODMACUID=$(${EXECC} ovn-nbctl --bare --columns=_uuid find static_mac_binding override_dynamic_mac=false |grep -v '^$')
    if [[ ${REVERT} != "revert" ]] && [[ -n ${ODMACUID} ]];then
      echo "$(date +%FT%T.%Z) CHANGING: Found $(wc -l <<< "${ODMACUID}") static_mac_binding with override_dynamic_mac=false, changing them..."
      while read uid ; do
        ${EXECC} ovn-nbctl set Static_MAC_Binding ${uid} override_dynamic_mac=true
      done <<< "${ODMACUID}"
    fi

    COUNT=$(( $COUNT + $(wc -l <<< "${NEIGHBORS}") ))

    TOTLRPORTS=$(${EXECC} ovn-nbctl --columns=name --bare find logical_router_port | grep rtoe-GR |wc -l)
    TOTBIND=$(${EXECC} ovn-nbctl --bare --columns=mac find static_mac_binding  |grep -Ecv "^$|0a:58:a9")
    [[ ${REVERT} == "revert" ]] && echo "$(date +%FT%T.%Z) In REVERT mode. VERIFICATION: total bindings ${TOTBIND} (expected 0)"
    [[ ${REVERT} != "revert" ]] && echo "$(date +%FT%T.%Z) VERIFICATION: total bindings ${TOTBIND} (expected $((${COUNT} * ${TOTLRPORTS})))"

    exit 0
