---
apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
  name: egressip-obj-{{.Iteration}}
spec:
  egressIPs:
  {{range (splitList " " (GetIPAddress .eipAddresses .Iteration .addrPerIteration))}}
  - {{.}}
  {{end}}
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: egressip-{{.Iteration}}
  podSelector:
    matchLabels:
      app: client
