apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pod-monitor-{{.Replica}}
spec:
  selector:
    matchLabels:
      app: client
  podMetricsEndpoints:
  - port: metrics
    interval: 15s
    scheme: http
