name: CI tests
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - main

jobs:
  codeql:
    uses: ./.github/workflows/codeql.yml

  lint:
    uses: ./.github/workflows/linters.yml

  build-matrix:
    uses: ./.github/workflows/build-matrix.yml
