
apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: l3-network-{{.Iteration}}
spec:
  topology: Layer3
  layer3:
      role: Primary
      subnets:
        - cidr: 10.132.0.0/16
          hostSubnet: 24
      mtu: 1300
